site_name: 名校公开课程评价网

theme:
  name: material
  custom_dir: overrides

repo_url: https://github.com/mike-box/OS-study

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true

plugins:
  - search:
      lang:
        - en
        - ja